name: Sync master and next-moc
on:
  push:
    branches:
      - sync-next-moc
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Merge master -> next-moc
        uses: ./.github/actions/sync-branch
        with:
          stable_branch: 'master'
          development_branch: 'next-moc'
          use_rebase: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
